version: '3.4'

services:
  sqlserver:  
    image: microsoft/mssql-server-linux
    #mcr.microsoft.com/mssql/server  
   # hostname: 'sqlserver'  
    environment:  
      ACCEPT_EULA: Y  
      SA_PASSWORD: "Password12!"  
    volumes:  
      - ./data/mssql:/var/opt/mssql3  
    ports:  
      - '1433:1433'  

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    environment:  
      - ASPNETCORE_ENVIRONMENT=Development  
    ports:  
      - "51417:80"
    depends_on:
      - sqlserver